function getLink(id, quarter){
  let conn = "https://www.washington.edu/students/timeschd/";
  conn = conn.concat(quarter);
  const x = mapList(id);
  if (x == "-1"){
    return "fail";
  }

  conn = conn.concat("/", x);
  return conn;
}

function mapList(id){
  const course = new Map([
    ["ARCTIC","arctic.html"],
    ["HONORS","hnrs.html"],
    ["LEAD","lead.html"],
    ["ACADEM","academ.html"],
    ["AFRAM","afamst.html"],
    ["AES","aes.html"],
    ["AAS","asamst.html"],
    ["CHSTU","chist.html"],
    ["SWA","swa.html"],
    ["TAGLG","taglg.html"],
    ["AIS","ais.html"],
    ["ANTH","anthro.html"],
    ["ARCHY","archeo.html"],
    ["BIO A","bioanth.html"],
    ["AMATH","appmath.html"],
    ["CFRM","cfrm.html"],
    ["ART","art.html"],
    ["ART H","arthis.html"],
    ["DESIGN","design.html"],
    ["ARTSCI","artsci.html"],
    ["ARTS","arts.html"],
    ["ASIAN","asianll.html"],
    ["BENG","beng.html"],
    ["CHIN","chinese.html"],
    ["HINDI","hindi.html"],
    ["INDN","indian.html"],
    ["INDO","indo.html"],
    ["JAPAN","japanese.html"],
    ["KOREAN","korean.html"],
    ["SNKRT","sanskrit.html"],
    ["S ASIA","sasian.html"],
    ["URDU","urdu.html"],
    ["VIET","viet.html"],
    ["ASTR","astro.html"],
    ["ASTBIO","astbio.html"],
    ["BIOL","biology.html"],
    ["BIOL","biology.html"],
    ["CS&SS","cs&ss.html"],
    ["CSDE","csde.html"],
    ["HUM","centhum.html"],
    ["CHEM","chem.html"],
    ["CMS","cms.html"],
    ["C LIT","complit.html"],
    ["CL AR","clarch.html"],
    ["CL LI","cling.html"],
    ["CLAS","clas.html"],
    ["GREEK","greek.html"],
    ["LATIN","latin.html"],
    ["COM","com.html"],
    ["COMMLD","commld.html"],
    ["CHID","chid.html"],
    ["RELIG","religion.html"],
    ["DANCE","dance.html"],
    ["DXARTS","dxarts.html"],
    ["DIS ST","disst.html"],
    ["DRAMA","drama.html"],
    ["ECON","econ.html"],
    ["ENGL","engl.html"],
    ["FRENCH","french.html"],
    ["ITAL","italian.html"],
    ["TXTDS","txtds.html"],
    ["GWSS","gwss.html"],
    ["GEN ST","genst.html"],
    ["GIS","gis.html"],
    ["INDIV","indiv.html"],
    ["GEOG","geog.html"],
    ["GERMAN","germ.html"],
    ["JSIS E","jsise.html"],
    ["HSTAM","ancmedh.html"],
    ["HSTCMP","hstcmp.html"],
    ["HSTAFM","hstafm.html"],
    ["HSTAS","histasia.html"],
    ["HSTLAC","hstlac.html"],
    ["HSTEU","modeuro.html"],
    ["HSTAA","histam.html"],
    ["HSTRY","hstry.html"],
    ["HUM","centhum.html"],
    ["INTSCI","intsci.html"],
    ["RELIG","religion.html"],
    ["JSIS","jsis.html"],
    ["JSIS A","jsisa.html"],
    ["JSIS B","jsisb.html"],
    ["JSIS C","jsisc.html"],
    ["JSIS D","jsisd.html"],
    ["JSIS E","jsise.html"],
    ["JEW ST","jewst.html"],
    ["LABOR","labor.html"],
    ["LSJ","lsj.html"],
    ["ASL","asl.html"],
    ["LING","ling.html"],
    ["LIT","lit.html"],
    ["MATH","math.html"],
    ["ARAB","arabic.html"],
    ["ARAMIC","aramic.html"],
    ["COPTIC","coptic.html"],
    ["EGYPT","egypt.html"],
    ["GEEZ","geez.html"],
    ["HEBR","hebrew.html"],
    ["BIBHEB","bibheb.html"],
    ["MODHEB","modheb.html"],
    ["NEAR E","neareast.html"],
    ["PRSAN","persian.html"],
    ["TURKIC","turkc.html"],
    ["CHGTAI","chgtai.html"],
    ["KAZAKH","kazakh.html"],
    ["KYRGYZ","kyrgyz.html"],
    ["UYGUR","uygur.html"],
    ["UZBEK","uzbek.html"],
    ["TKISH","turkish.html"],
    ["UGARIT","ugarit.html"],
    ["MUSIC","music.html"],
    ["MUSAP","appmus.html"],
    ["MUSED","mused.html"],
    ["MUSEN","musensem.html"],
    ["MUHST","mushist.html"],
    ["MUSICP","musicp.html"],
    ["NBIO","nbio.html"],
    ["NEUSCI","neusci.html"],
    ["ETHICS","ethics.html"],
    ["HPS","hps.html"],
    ["PHIL","phil.html"],
    ["PHYS","phys.html"],
    ["POL S","polisci.html"],
    ["PSYCAP","95psycap.html"],
    ["PSYCLN","psycln.html"],
    ["PSYCH","psych.html"],
    ["DANISH","danish.html"],
    ["ESTO","eston.html"],
    ["FINN","finnish.html"],
    ["ICEL","icel.html"],
    ["LATV","latvian.html"],
    ["LITH","lith.html"],
    ["NORW","norweg.html"],
    ["SCAND","scand.html"],
    ["SWED","swedish.html"],
    ["BCMS","bcms.html"],
    ["BULGR","bulgar.html"],
    ["CZECH","czech.html"],
    ["GEORG","georg.html"],
    ["GLITS","glits.html"],
    ["POLSH","polish.html"],
    ["ROMN","romanian.html"],
    ["RUSS","russian.html"],
    ["SLAVIC","slavic.html"],
    ["SLVN","slvn.html"],
    ["UKR","ukrain.html"],
    ["SOCSCI","socsci.html"],
    ["SOC","soc.html"],
    ["PORT","port.html"],
    ["SPAN","spanish.html"],
    ["SPLING","spanlin.html"],
    ["SPHSC","sphsc.html"],
    ["STAT","stat.html"],
    ["BIOL","biology.html"],
    ["ARCH","archit.html"],
    ["B E","be.html"],
    ["CM","constmgmt.html"],
    ["L ARCH","landscape.html"],
    ["R E","re.html"],
    ["CEP","commenv.html"],
    ["IPM","ipm.html"],
    ["URBDP","urbdes.html"],
    ["ACCTG","acctg.html"],
    ["ADMIN","admin.html"],
    ["B A","ba.html"],
    ["BA RM","barm.html"],
    ["BUS AN","busan.html"],
    ["B CMU","buscomm.html"],
    ["B ECON","busecon.html"],
    ["B POL","bpol.html"],
    ["EBIZ","ebiz.html"],
    ["ENTRE","entre.html"],
    ["FIN","finance.html"],
    ["HRMOB","hrmob.html"],
    ["I S","infosys.html"],
    ["MSIS","msis.html"],
    ["I BUS","intlbus.html"],
    ["MGMT","mgmt.html"],
    ["MKTG","mktg.html"],
    ["OPMGT","opmgmt.html"],
    ["O E","orgenv.html"],
    ["QMETH","qmeth.html"],
    ["ST MGT","stratm.html"],
    ["SCM","scm.html"],
    ["DENTCL","dentcl.html"],
    ["DENTEL","dentel.html"],
    ["DENTFN","dentfn.html"],
    ["DENTGP","dentgp.html"],
    ["D HYG","denthy.html"],
    ["DENTPC","dentpc.html"],
    ["DENTSL","dentsl.html"],
    ["DPHS","dphs.html"],
    ["DENT","dent.html"],
    ["ENDO","endo.html"],
    ["ORALB","oralbio.html"],
    ["OHS","ohs.html"],
    ["ORALM","oralm.html"],
    ["O S","os.html"],
    ["ORTHO","orthod.html"],
    ["PEDO","pedodon.html"],
    ["PERIO","perio.html"],
    ["PROS","pros.html"],
    ["RES D","restor.html"],
    ["EDC&I","edci.html"],
    ["EDUC","indsrf.html"],
    ["ECE","ece.html"],
    ["ECFS","ecfs.html"],
    ["EDTEP","teached.html"],
    ["EDLPS","edlp.html"],
    ["EDPSY","edpsy.html"],
    ["EDSPE","sped.html"],
    ["A A","aa.html"],
    ["A E","ae.html"],
    ["CHEM E","cheng.html"],
    ["NME","nme.html"],
    ["CEE","cee.html"],
    ["CESI","cesi.html"],
    ["CEWA","cewa.html"],
    ["CESG","cesg.html"],
    ["CET","cet.html"],
    ["CSE","cse.html"],
    ["CSE D","csed.html"],
    ["E E","ee.html"],
    ["ENGR","engr.html"],
    ["HCDE","hcde.html"],
    ["IND E","inde.html"],
    ["MS E","mse.html"],
    ["M E","meche.html"],
    ["MEIE","meie.html"],
    ["FISH","fish.html"],
    ["ATM S","atmos.html"],
    ["C ENV","cenv.html"],
    ["SCI T","scit.html"],
    ["ESS","ess.html"],
    ["ENVIR","envst.html"],
    ["BSE","bse.html"],
    ["ESRM","esrm.html"],
    ["SEFS","sefs.html"],
    ["FHL","fhl.html"],
    ["SMEA","smea.html"],
    ["MARBIO","marbio.html"],
    ["OCEAN","ocean.html"],
    ["Q SCI","quantsci.html"],
    ["QERM","quante.html"],
    ["QUAT","qrc.html"],
    ["INFO","info.html"],
    ["INSC","insc.html"],
    ["IMT","imt.html"],
    ["LIS","lis.html"],
    ["BPSD","bpsd.html"],
    ["DATA","data.html"],
    ["GRDSCH","grad.html"],
    ["HCID","hcid.html"],
    ["HDD","hdd.html"],
    ["IPHD","iphd.html"],
    ["MCB","mcb.html"],
    ["MOLENG","moleng.html"],
    ["MUSEUM","museo.html"],
    ["N&MES","nearmide.html"],
    ["NEURO","neuro.html"],
    ["PUBSCH","pubsch.html"],
    ["STSS","stss.html"],
    ["TECHIN","techin.html"],
    ["BIOEN","bioeng.html"],
    ["MEDENG","medeng.html"],
    ["PHARBE","pharbe.html"],
    ["G H","gh.html"],
    ["UCONJ","uconjoint.html"],
    ["LAW","law.html"],
    ["LAW A","lawa.html"],
    ["LAW B","lawb.html"],
    ["LAW C","lawc.html"],
    ["LAW E","lawe.html"],
    ["LAW H","lawh.html"],
    ["LAW P","lawp.html"],
    ["LAW T","lawt.html"],
    ["ANEST","anest.html"],
    ["BIOC","bioch.html"],
    ["B H","bh.html"],
    ["B STR","biostruct.html"],
    ["BIME","bime.html"],
    ["C MED","compmed.html"],
    ["CONJ","conj.html"],
    ["FAMED","famed.html"],
    ["MEDLIC","medlic.html"],
    ["GENOME","genome.html"],
    ["HMS","hms.html"],
    ["HUBIO","humbio.html"],
    ["IMMUN","immun.html"],
    ["LAB M","labmed.html"],
    ["PATH","patho.html"],
    ["MEDSCI","medsci.html"],
    ["MED EM","medem.html"],
    ["GCNSL","gcnsl.html"],
    ["MED","medicine.html"],
    ["MEDECK","medeck.html"],
    ["MEDRCK","medrck.html"],
    ["MICROM","microbio.html"],
    ["MOLMED","molmed.html"],
    ["NEUR S","neurosurg.html"],
    ["NEURL","neurl.html"],
    ["OB GYN","obgyn.html"],
    ["OPHTH","ophthal.html"],
    ["ORTHP","orthop.html"],
    ["OTOHN","otol.html"],
    ["PEDS","pediat.html"],
    ["PHCOL","pharma.html"],
    ["P BIO","physiolbio.html"],
    ["PBSCI","psychbehav.html"],
    ["R ONC","radonc.html"],
    ["RADGY","radiol.html"],
    ["RHB PO","rhbpo.html"],
    ["REHAB","rehab.html"],
    ["SURG","surg.html"],
    ["UROL","uro.html"],
    ["IECMH","iecmh.html"],
    ["NSG","nsg.html"],
    ["NURS","nursing.html"],
    ["NCLIN","nursingcl.html"],
    ["NMETH","nursingmeth.html"],
    ["HEOR","heor.html"],
    ["MEDCH","medchem.html"],
    ["PCEUT","pharmceu.html"],
    ["PHARM","pharmacy.html"],
    ["PHRMCY","phrmcy.html"],
    ["PHARMP","pharmp.html"],
    ["PHRMPR","phrmpr.html"],
    ["PHRMRA","phrmra.html"],
    ["PUBPOL","pubpol.html"],
    ["PPM","ppm.html"],
    ["BIOST","biostat.html"],
    ["ENV H","envh.html"],
    ["EPI","epidem.html"],
    ["HIHIM","95hihim.html"],
    ["HSERV","hlthsvcs.html"],
    ["HSMGMT","hsmgmt.html"],
    ["NUTR","nutrit.html"],
    ["PABIO","pathobio.html"],
    ["PHG","phg.html"],
    ["PHI","phi.html"],
    ["SPH","sph.html"],
    ["A S","88aerosci.html"],
    ["M SCI","88milsci.html"],
    ["N SCI","88navsci.html"],
    ["SOC WF","socwlbasw.html"],
    ["SOC WL","socwl.html"],
    ["SOC W","socwk.html"],
  ]);

  if (course.has(id)){
    return course.get(id);
  } else{
    return "-1";
  }

}