name: ci

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cd build && ./build.sh
      - name: Test
        uses: actions/setup-node@v2
        with:
          node-version: 16
        run: npm ci && npm test