name: ci

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: cd build && ./build.sh
      - name: Test
        with:
          node-version: 16
        run: npm ci
        run: npm test